services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash ./.docker/start.sh
    container_name: bnck-admin-catalogo
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
