services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bnck-admin-catalogo-py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
